version: '3.8'

services:

  som-model:
    build:
      context: ./som-model
    environment:
      RABBITMQ_URL: amqp://guest:guest@34.231.140.237

  valuation-model:
    build:
      context: ./valuation-model
    environment:
      RABBITMQ_URL: amqp://guest:guest@34.231.140.237

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@34.231.140.237
