"""
Endpoints
Subscription:
- taskUpdated:
    - Frontend subscribes to receive Task object update

Mutation:
- createTask:
    - Used for submitting task request
    - Returns Task object

Input
- CreateTask
    - id
    - desc
    - folderPath
    - wallet address

Type (outputs)
- Task
    - id
    - desc
    - folderPath
    - wallet address
    - status
    - valuation
"""
type Query {
  _empty: String
}

type Subscription {
  taskUpdated(folderPath: String!): Task
}

type Mutation {
  createTask(input: CreateTaskInput!): Task
}

input CreateTaskInput {
  id: ID!
  desc: String!
  folderPath: String!
  walletAddress: String!
}

type Task {
  id: ID!
  desc: String!
  cid: String
  folderPath: String!
  walletAddress: String!
  status: String!
  valuation: String
  message: String
}
